# Generated by Django 4.1.3 on 2022-11-15 14:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('correlation_id', models.CharField(editable=False, max_length=36, verbose_name='Correlation ID')),
                ('action', models.CharField(editable=False, max_length=128, verbose_name='Action')),
                ('metadata', models.JSONField(editable=False, verbose_name='Metadata')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
