# https://auth0.com/docs/deploy-monitor/logs/log-event-type-codes

auth0_log_events_samples = [
    {
        "date": "2022-04-12T19:45:49.379Z",
        "type": "sapi",
        "description": "Update a connection",
        "client_id": "UegcnFxLgYbJSVwQEv82cgv9B4Bq6poZ",
        "client_name": "",
        "ip": "35.167.74.121",
        "user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36",
        "details": {
            "request": {
                "method": "patch",
                "path": "/api/v2/connections/con_Budg1kY9GWs5U07r",
                "query": {},
                "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36",
                "body": {},
                "channel": "https://manage.auth0.com/",
                "ip": "35.167.74.121",
                "auth": {
                    "user": {
                        "user_id": "auth0|61e85d76c719b10069a5a28e",
                        "name": "identity",
                        "email": "identity@willianantunes.com",
                    },
                    "strategy": "jwt",
                    "credentials": {
                        "jti": "de2861d6f369e06f4c686a3633844b4b",
                        "scopes": [
                            "create:actions",
                            "create:client_grants",
                            "create:clients",
                            "create:connections",
                            "create:custom_domains",
                            "create:email_provider",
                            "create:email_templates",
                            "create:guardian_enrollment_tickets",
                            "create:integrations",
                            "create:log_streams",
                            "create:organization_connections",
                            "create:organization_invitations",
                            "create:organization_member_roles",
                            "create:organization_members",
                            "create:organizations",
                            "create:requested_scopes",
                            "create:resource_servers",
                            "create:roles",
                            "create:rules",
                            "create:shields",
                            "create:signing_keys",
                            "create:tenant_invitations",
                            "create:test_email_dispatch",
                            "create:users",
                            "delete:actions",
                            "delete:anomaly_blocks",
                            "delete:branding",
                            "delete:client_grants",
                            "delete:clients",
                            "delete:connections",
                            "delete:custom_domains",
                            "delete:device_credentials",
                            "delete:email_provider",
                            "delete:email_templates",
                            "delete:grants",
                            "delete:guardian_enrollments",
                            "delete:integrations",
                            "delete:log_streams",
                            "delete:organization_connections",
                            "delete:organization_invitations",
                            "delete:organization_member_roles",
                            "delete:organization_members",
                            "delete:organizations",
                            "delete:owners",
                            "delete:requested_scopes",
                            "delete:resource_servers",
                            "delete:roles",
                            "delete:rules",
                            "delete:rules_configs",
                            "delete:shields",
                            "delete:tenant_invitations",
                            "delete:tenant_members",
                            "delete:tenants",
                            "delete:users",
                            "read:actions",
                            "read:anomaly_blocks",
                            "read:attack_protection",
                            "read:branding",
                            "read:checks",
                            "read:client_grants",
                            "read:client_keys",
                            "read:clients",
                            "read:connections",
                            "read:custom_domains",
                            "read:device_credentials",
                            "read:email_provider",
                            "read:email_templates",
                            "read:email_triggers",
                            "read:entity_counts",
                            "read:grants",
                            "read:guardian_factors",
                            "read:insights",
                            "read:integrations",
                            "read:log_streams",
                            "read:logs",
                            "read:mfa_policies",
                            "read:organization_connections",
                            "read:organization_invitations",
                            "read:organization_member_roles",
                            "read:organization_members",
                            "read:organizations",
                            "read:prompts",
                            "read:requested_scopes",
                            "read:resource_servers",
                            "read:roles",
                            "read:rules",
                            "read:rules_configs",
                            "read:shields",
                            "read:signing_keys",
                            "read:stats",
                            "read:tenant_invitations",
                            "read:tenant_members",
                            "read:tenant_settings",
                            "read:triggers",
                            "read:users",
                            "run:checks",
                            "update:actions",
                            "update:attack_protection",
                            "update:branding",
                            "update:client_grants",
                            "update:client_keys",
                            "update:clients",
                            "update:connections",
                            "update:custom_domains",
                            "update:email_provider",
                            "update:email_templates",
                            "update:email_triggers",
                            "update:guardian_factors",
                            "update:integrations",
                            "update:log_streams",
                            "update:mfa_policies",
                            "update:organization_connections",
                            "update:organizations",
                            "update:prompts",
                            "update:requested_scopes",
                            "update:resource_servers",
                            "update:roles",
                            "update:rules",
                            "update:rules_configs",
                            "update:shields",
                            "update:signing_keys",
                            "update:tenant_members",
                            "update:tenant_settings",
                            "update:triggers",
                            "update:users",
                        ],
                    },
                },
            },
            "response": {
                "statusCode": 200,
                "body": {
                    "id": "con_Budg1kY9GWs5U07r",
                    "strategy": "auth0",
                    "name": "agrabah-users-connection",
                    "enabled_clients": [],
                    "realms": ["agrabah-users-connection"],
                },
            },
        },
        "user_id": "auth0|61e85d76c719b10069a5a28e",
        "log_id": "90020220412194551761922609558062620207705485484950028290",
    },
    {
        "date": "2022-04-12T19:39:08.685Z",
        "type": "api_limit",
        "description": "Global limit has been reached",
        "client_id": "0K4d0DgZthpVjPgZ2T9lLvqMSqweveLt",
        "client_name": "",
        "details": {
            "request": {"method": "put", "path": "/api/v2/guardian/factors/phone/message-types"},
            "response": {},
        },
        "log_id": "90020220412193913718263179448677847085495305233521180690",
    },
    {
        "date": "2022-04-12T19:39:07.148Z",
        "type": "seccft",
        "description": "",
        "connection_id": "",
        "client_id": "0K4d0DgZthpVjPgZ2T9lLvqMSqweveLt",
        "client_name": "Tenant management - M2M - sensoji-temple",
        "ip": "20.22.197.170",
        "user_agent": "node.js/14.19.1",
        "hostname": "cockatieldev.us.auth0.com",
        "user_id": "",
        "user_name": "",
        "audience": "https://cockatieldev.us.auth0.com/api/v2/",
        "scope": "read:client_grants create:client_grants delete:client_grants update:client_grants read:clients update:clients delete:clients create:clients read:client_keys update:client_keys delete:client_keys create:client_keys read:connections update:connections delete:connections create:connections read:resource_servers update:resource_servers delete:resource_servers create:resource_servers read:rules update:rules delete:rules create:rules read:rules_configs update:rules_configs delete:rules_configs read:hooks update:hooks delete:hooks create:hooks read:actions update:actions delete:actions create:actions read:email_provider update:email_provider delete:email_provider create:email_provider read:tenant_settings update:tenant_settings read:grants delete:grants read:guardian_factors update:guardian_factors read:email_templates create:email_templates update:email_templates read:mfa_policies update:mfa_policies read:roles create:roles delete:roles update:roles read:prompts update:prompts read:branding update:branding read:organizations update:organizations create:organizations delete:organizations create:organization_connections read:organization_connections update:organization_connections delete:organization_connections",
        "auth0_client": {"name": "node-auth0", "version": "2.37.0", "env": {"node": "14.19.1"}},
        "log_id": "90020220412193910488922608580580813055018580203062427650",
    },
    {
        "date": "2022-04-06T13:39:50.144Z",
        "type": "s",
        "connection": "Username-Password-Authentication",
        "connection_id": "con_dKkvABJlA29FWlKd",
        "client_id": "Rx1g3skPruIbVKqYgFVa3SO9QiOKsAbm",
        "client_name": "Temporary My App",
        "ip": "3.220.150.63",
        "user_agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.83 Safari/537.36",
        "details": {
            "prompts": [
                {
                    "name": "prompt-authenticate",
                    "completedAt": 1649252389653,
                    "connection": "Username-Password-Authentication",
                    "connection_id": "con_dKkvABJlA29FWlKd",
                    "strategy": "auth0",
                    "identity": "624d97dd754ef9006f7a3785",
                    "stats": {"loginsCount": 2},
                    "elapsedTime": None,
                },
                {
                    "name": "login",
                    "flow": "universal-login",
                    "initiatedAt": 1649252377363,
                    "completedAt": 1649252389687,
                    "timers": {"rules": 3},
                    "user_id": "auth0|624d97dd754ef9006f7a3785",
                    "user_name": "agrabah@willianantunes.com",
                    "elapsedTime": 12324,
                },
            ],
            "initiatedAt": 1649252377350,
            "completedAt": 1649252390142,
            "elapsedTime": 12792,
            "session_id": "-GAziI89zWRS0EnBehiV0BwGYsy7UDzm",
            "stats": {"loginsCount": 2},
        },
        "hostname": "cockatieldev.us.auth0.com",
        "user_id": "auth0|624d97dd754ef9006f7a3785",
        "user_name": "agrabah@willianantunes.com",
        "strategy": "auth0",
        "strategy_type": "database",
        "log_id": "90020220406133952825262863733443426914186115554140487698",
    },
    {
        "date": "2022-04-06T13:39:35.220Z",
        "type": "slo",
        "connection": "Username-Password-Authentication",
        "connection_id": "con_dKkvABJlA29FWlKd",
        "client_id": "Rx1g3skPruIbVKqYgFVa3SO9QiOKsAbm",
        "client_name": "Temporary My App",
        "ip": "3.220.150.63",
        "user_agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.83 Safari/537.36",
        "details": {
            "return_to": "http://app.local:8000/logout",
            "allowed_logout_url": ["http://app.local:8000/", "http://app.local:8000/logout"],
            "session_id": "crk4ShpUyZC-cAURvl-pNWQU1QuWJK_5",
        },
        "hostname": "cockatieldev.us.auth0.com",
        "user_id": "auth0|624d97dd754ef9006f7a3785",
        "user_name": "agrabah@willianantunes.com",
        "log_id": "90020220406133935711262863723212287702787507611651538962",
    },
    {
        "date": "2022-04-06T13:38:37.344Z",
        "type": "ss",
        "description": "",
        "connection": "Username-Password-Authentication",
        "connection_id": "con_dKkvABJlA29FWlKd",
        "client_id": "Rx1g3skPruIbVKqYgFVa3SO9QiOKsAbm",
        "client_name": "Temporary My App",
        "ip": "3.220.150.63",
        "user_agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.83 Safari/537.36",
        "details": {
            "body": {
                "connection": "Username-Password-Authentication",
                "client_id": "Rx1g3skPruIbVKqYgFVa3SO9QiOKsAbm",
                "email": "agrabah@willianantunes.com",
                "password": "*****",
                "tenant": "cockatieldev",
                "transaction": {
                    "id": "lmiJmerKiNWXvF9ovK6IPTk5QW0l4c3P",
                    "locale": "pt-BR",
                    "protocol": "oidc-basic-profile",
                    "requested_scopes": ["openid", "profile", "email"],
                    "acr_values": [],
                    "ui_locales": [],
                    "redirect_uri": "http://app.local:8000/api/v1/response-oidc",
                    "prompt": [],
                    "state": "965fbb58-a37d-4268-8e14-3baf7971a62b",
                    "login_hint": None,
                    "response_mode": None,
                    "response_type": ["code"],
                },
                "request_language": "en-US,en;q=0.9,pt-BR;q=0.8,pt;q=0.7",
            }
        },
        "user_id": "auth0|624d97dd754ef9006f7a3785",
        "user_name": "agrabah@willianantunes.com",
        "strategy": "auth0",
        "strategy_type": "database",
        "log_id": "90020220406133840374262863680862407315867429212948267026",
    },
    {
        "date": "2022-04-06T13:36:48.618Z",
        "type": "f",
        "description": "Callback URL mismatch. http://app.local:8000/api/v1/response-oidc is not in the list of allowed callback URLs",
        "connection_id": "",
        "ip": "3.220.150.63",
        "user_agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.83 Safari/537.36",
        "details": {
            "body": {},
            "qs": {
                "state": "14120647-21a8-4813-ad13-626daa9d43a7",
                "client_id": "Rx1g3skPruIbVKqYgFVa3SO9QiOKsAbm",
                "response_type": "code",
                "redirect_uri": "http://app.local:8000/api/v1/response-oidc",
                "scope": "openid profile email",
            },
            "error": {
                "message": "Callback URL mismatch. http://app.local:8000/api/v1/response-oidc is not in the list of allowed callback URLs",
                "oauthError": "Callback URL mismatch. http://app.local:8000/api/v1/response-oidc is not in the list of allowed callback URLs. Please go to 'https://manage.auth0.com/#/applications/Rx1g3skPruIbVKqYgFVa3SO9QiOKsAbm/settings' and make sure you are sending the same callback url from your application.",
                "payload": {
                    "message": "Callback URL mismatch. http://app.local:8000/api/v1/response-oidc is not in the list of allowed callback URLs",
                    "code": "unauthorized_client",
                    "status": 403,
                    "name": "CallbackMismatchError",
                    "authorized": ["http://app.local:8000/"],
                    "attempt": "http://app.local:8000/api/v1/response-oidc",
                    "client": {"clientID": "Rx1g3skPruIbVKqYgFVa3SO9QiOKsAbm"},
                    "log_url": "https://manage.auth0.com/#/logs/",
                },
                "type": "callback-url-mismatch",
            },
        },
        "hostname": "cockatieldev.us.auth0.com",
        "log_id": "90020220406133650198262863598001422713661123390269816850",
    },
    {
        "date": "2022-04-06T13:34:46.744Z",
        "type": "mgmt_api_read",
        "description": "Get a client",
        "client_id": "UegcnFxLgYbJSVwQEv82cgv9B4Bq6poZ",
        "client_name": "",
        "ip": "35.167.74.121",
        "user_agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.83 Safari/537.36",
        "details": {
            "accessedSecrets": ["client_secret"],
            "request": {
                "method": "get",
                "path": "/api/v2/clients/Rx1g3skPruIbVKqYgFVa3SO9QiOKsAbm",
                "query": {},
                "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.83 Safari/537.36",
                "body": None,
                "channel": "https://manage.auth0.com/",
                "ip": "35.167.74.121",
                "auth": {
                    "user": {
                        "user_id": "github|4432783",
                        "name": "Willian Antunes",
                        "email": "willian.lima.antunes@gmail.com",
                    },
                    "strategy": "jwt",
                    "credentials": {"jti": "6ffdc25706d0978ef15430a3e321248b"},
                },
            },
            "response": {"statusCode": 200, "body": {"client_id": "Rx1g3skPruIbVKqYgFVa3SO9QiOKsAbm"}},
        },
        "user_id": "github|4432783",
        "log_id": "90020220406133447564921656118762869403449859412726906882",
    },
    {
        "date": "2022-03-29T14:11:19.377Z",
        "type": "gd_tenant_update",
        "description": "Guardian - Updates tenant settings",
        "ip": "20.106.133.136",
        "details": {
            "request": {
                "method": "PATCH",
                "path": "/api/tenants/settings",
                "query": {},
                "body": {"friendly_name": "[REDACTED]", "picture_url": "[REDACTED]"},
                "ip": "20.106.133.136",
                "auth": {
                    "subject": "0K4d0DgZthpVjPgZ2T9lLvqMSqweveLt@clients",
                    "strategy": "jwt_api2_internal_token",
                    "scopes": [
                        "read:authenticators",
                        "remove:authenticators",
                        "update:authenticators",
                        "create:authenticators",
                        "read:enrollments",
                        "delete:enrollments",
                        "read:factors",
                        "update:factors",
                        "update:tenant_settings",
                        "update:users",
                        "create:enrollment_tickets",
                        "create:users",
                    ],
                },
            },
            "response": {
                "body": {
                    "name": "cockatieldev",
                    "friendly_name": "[REDACTED]",
                    "picture_url": "[REDACTED]",
                    "guardian_mfa_page": "[REDACTED]",
                },
                "statusCode": 200,
            },
        },
        "user_id": "0K4d0DgZthpVjPgZ2T9lLvqMSqweveLt@clients",
        "log_id": "90020220329141120410262432576880292237466242273612136466",
    },
    {
        "date": "2022-04-06T13:38:42.750Z",
        "type": "flo",
        "description": 'The "returnTo" querystring parameter "http://app.local:8000/logout" is not defined as a valid URL in "Allowed Logout URLs". To add a new URL, please do it here: https://manage.auth0.com/#/applications/Rx1g3skPruIbVKqYgFVa3SO9QiOKsAbm/settings',
        "connection": "Username-Password-Authentication",
        "connection_id": "con_dKkvABJlA29FWlKd",
        "client_id": "Rx1g3skPruIbVKqYgFVa3SO9QiOKsAbm",
        "client_name": "Temporary My App",
        "ip": "3.220.150.63",
        "user_agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.83 Safari/537.36",
        "details": {
            "return_to": "http://app.local:8000/logout",
            "allowed_logout_url": ["http://app.local:8000/"],
            "session_id": "crk4ShpUyZC-cAURvl-pNWQU1QuWJK_5",
        },
        "hostname": "cockatieldev.us.auth0.com",
        "user_id": "auth0|624d97dd754ef9006f7a3785",
        "user_name": "agrabah@willianantunes.com",
        "log_id": "90020220406133846342262863684034628666536216579694133266",
    },
]
