# Generated by Django 4.0.3 on 2022-04-06 23:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('language_tag', models.CharField(max_length=20, unique=True)),
                ('language', models.CharField(blank=True, max_length=50, null=True, verbose_name='Language')),
                ('accent_or_dialect', models.CharField(blank=True, max_length=50, null=True, verbose_name='Accent/Dialect')),
                ('family', models.CharField(blank=True, max_length=50, null=True, verbose_name='Family')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('screen_name', models.CharField(max_length=16)),
                ('when_tweet_was_created', models.DateTimeField()),
                ('tweet_id', models.PositiveBigIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
