image:
  repository: registry.k8s.io/metrics-server/metrics-server
  # https://github.com/kubernetes-sigs/metrics-server/issues/1468#issuecomment-2109843985
  tag: "v0.6.4"
  pullPolicy: IfNotPresent

defaultArgs:
  - --cert-dir=/tmp
  - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
  - --kubelet-use-node-status-port
  - --metric-resolution=15s
  - --kubelet-insecure-tls=true
